language: node_js
sudo: false

matrix:
    include:
        - node_js: "lts/*"
          addons:
              chrome: stable
              firefox: latest-esr
          before_install:
              - npm install grunt-cli -g
          before_script:
              - export DISPLAY=:99.0
              - sh -e /etc/init.d/xvfb start
              - sleep 3 # give xvfb some time to start
          script:
              - grunt ci
        - node_js: "6"
          before_install:
              - npm install grunt-cli -g
          script:
              - ./node_modules/istanbul/lib/cli.js cover -- ./node_modules/jasmine/bin/jasmine.js --config=jasmine.json
          after_script:
              - grunt coveralls:librarynode
        - node_js: "lts/*"
          before_install:
              - npm install grunt-cli -g
          script:
              - ./node_modules/istanbul/lib/cli.js cover -- ./node_modules/jasmine/bin/jasmine.js --config=jasmine.json
          after_script:
              - grunt coveralls:librarynode
        - node_js: "10"
          before_install:
              - npm install grunt-cli -g
          script:
              - ./node_modules/istanbul/lib/cli.js cover -- ./node_modules/jasmine/bin/jasmine.js --config=jasmine.json
          after_script:
              - grunt coveralls:librarynode

branches:
  only:
    - master
