language: node_js
node_js:
    - "lts/*"
sudo: false
addons:
    chrome: stable
    firefox: latest-esr
before_script:
    - npm install grunt-cli -g
script:
    - grunt karma
branches:
  only:
    - master
